language: java
jdk:
  - openjdk7
  - oraclejdk7

install: "mvn -DskipTests=true install"

script: "mvn -Ptravis install"

notifications:
  email:
    recipients:
      - ksclarke@gmail.com
    on_failure: change
    on_success: change
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always
