language: java

jdk:
  - openjdk7
  - oraclejdk7

install: "mvn -DskipTests=true install"

script:
 - sudo ln -s . /opt/solr-jetty-maven
 - etc/init.d/solr start
 - sleep 30
 - test "200" == $(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8983/solr/admin/ping")
 - mvn -Ptravis install

notifications:
  email:
    recipients:
      - ksclarke@gmail.com
    on_failure: change
    on_success: change
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always
