language: java
jdk:
  - openjdk7
  - oraclejdk7

install: "mvn -DskipTests=true install"

script:
 - mvn -Ptravis install
 - sudo cp -r ../solr-jetty-maven /opt
 - sudo etc/init.d/solr start
 - sleep 30
 - test "200" == $(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8983/solr/admin/ping")

notifications:
  email:
    recipients:
      - ksclarke@gmail.com
    on_failure: change
    on_success: change
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always
